import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "../components/SessionWrapper";
import { GlobalSearchProvider } from "./context/GlobalSearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalSearchProvider>
          <SessionWrapper>{children}</SessionWrapper>
        </GlobalSearchProvider>
      </body>
    </html>
  );
}
